FROM node:5.12
MAINTAINER Long Nguyen <tobernguyen@gmail.com>
ENV REFRESHED_AT 2016-08-15

RUN apt-get -y update && \
    apt-get -y install graphicsmagick

RUN useradd --user-group --create-home --shell /bin/false app

ENV HOME=/home/app

COPY package.json npm-shrinkwrap.json $HOME/api/
RUN chown -R app:app $HOME/*

USER app
WORKDIR $HOME/api
RUN npm install --production

USER root
COPY . $HOME/api
RUN chown -R app:app $HOME/*

USER app
CMD ["node", "app.js"]
